microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /idpaywallet/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  envConfig:
    MONGODB_DBNAME: idpay
    APPLICATIONINSIGHTS_ROLE_NAME: "idpaywallet"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    INITIATIVE_LOGO_URL: "https://idpaydinitiativestorage.blob.core.windows.net/logo/"
    IS_IBAN_FORMAL_CONTROL_ACTIVE: "false"
    DELETE_PAGINATION_SIZE: "100"
    DELETE_DELAY_TIME: "1000"
    HEALTH_MONGO_ENABLED: "false"

  externalConfigMapValues:
    idpay-common:
      TZ: TZ
    rest-client:
      PAYMENT_INSTRUMENT_URI: idpay_payment_instrument_host
      ONBOARDING_URI: idpay_onboarding_host
      IDPAY_INITIATIVE_BASE_URL: initiative_ms_base_url
    idpay-eventhub-00:
      KAFKA_BINDER_BROKER_ENDPOINT_LIST: kafka_broker
      KAFKA_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_TOPIC_IBAN: idpay_checkiban_evaluation_topic
      KAFKA_TOPIC_OUTCOME: idpay_onboarding_outcome_topic
      KAFKA_TOPIC_CHECKIBAN_OUTCOME: idpay_checkiban_outcome_topic
      KAFKA_TOPIC_NOTIFICATION: idpay_notification_request_topic
      KAFKA_CHECKIBAN_OUTCOME_GROUP_IN: idpay-checkiban-outcome-consumer-group
      KAFKA_OUTCOME_GROUP_IN: idpay-onboarding-outcome-wallet-consumer-group
      KAFKA_TOPIC_RULE_ENGINE: idpay_transaction_topic
      KAFKA_RULE_ENGINE_GROUP_IN: idpay_transaction_wallet_consumer_group

    idpay-eventhub-01:
      KAFKA_BINDER_BROKER_ENDPOINT_LIST_01: kafka_broker
      KAFKA_TOPIC_REWARD: idpay_reward_notification_response_topic
      KAFKA_TOPIC_ERRORS: idpay_error_topic
      KAFKA_REWARD_GROUP_IN: idpay_reward_notification_response_consumer_group
      KAFKA_TOPIC_TIMELINE: idpay_timeline_topic

  envSecret:
    MONGODB_URI: mongodb-connection-string
    KAFKA_CHECKIBAN_OUTCOME_SASL_JAAS_CONFIG: evh-idpay-checkiban-outcome-idpay-checkiban-outcome-consumer-jaas-config-idpay-00
    KAFKA_IBAN_SASL_JAAS_CONFIG: evh-idpay-checkiban-evaluation-idpay-checkiban-evaluation-producer-jaas-config-idpay-00
    KAFKA_TIMELINE_SASL_JAAS_CONFIG: evh-idpay-timeline-idpay-timeline-producer-jaas-config-idpay-01
    KAFKA_OUTCOME_SASL_JAAS_CONFIG: evh-idpay-onboarding-outcome-idpay-onboarding-outcome-consumer-jaas-config-idpay-00
    KAFKA_RULE_ENGINE_SASL_JAAS_CONFIG: evh-idpay-transaction-idpay-transaction-consumer-jaas-config-idpay-00
    KAFKA_REWARD_SASL_JAAS_CONFIG: evh-idpay-reward-notification-response-idpay-reward-notification-response-consumer-jaas-config-idpay-01
    KAFKA_NOTIFICATION_SASL_JAAS_CONFIG: evh-idpay-notification-request-idpay-notification-request-producer-jaas-config-idpay-00
    KAFKA_ERRORS_SASL_JAAS_CONFIG: evh-idpay-errors-idpay-errors-producer-jaas-config-idpay-01
    KAFKA_COMMANDS_SASL_JAAS_CONFIG: evh-idpay-commands-idpay-commands-consumer-jaas-config-idpay-01

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json